INSERT INTO "DEPARTMENT" ("NAME") VALUES ('TestDep_1'); -- ID: 1
INSERT INTO "DEPARTMENT" ("NAME") VALUES ('TestDep_2'); -- ID: 2
INSERT INTO "DEPARTMENT" ("NAME") VALUES ('TestDep_3'); -- ID: 3
INSERT INTO "DEPARTMENT" ("NAME") VALUES ('TestDep_4'); -- ID: 4
INSERT INTO "DEPARTMENT" ("NAME") VALUES ('TestDep_5'); -- ID: 5
INSERT INTO "DEPARTMENT" ("NAME") VALUES ('TestDep_6'); -- ID: 6

INSERT INTO "EMPLOYEE" ("ID", "DEPARTMENT_ID", "CHIEF_ID", "NAME", "SALARY") VALUES (0, 1, 0, 'CEO', 99999999999999); --ID: 0

INSERT INTO "EMPLOYEE" ("DEPARTMENT_ID", "CHIEF_ID", "NAME", "SALARY") VALUES (1, 0, 'CEO_TestDep_1', 99999999); -- ID: 1
INSERT INTO "EMPLOYEE" ("DEPARTMENT_ID", "CHIEF_ID", "NAME", "SALARY") VALUES (2, 0, 'CEO_TestDep_2', 99999999); -- ID: 2
INSERT INTO "EMPLOYEE" ("DEPARTMENT_ID", "CHIEF_ID", "NAME", "SALARY") VALUES (3, 0, 'CEO_TestDep_3', 99999999); -- ID: 3
INSERT INTO "EMPLOYEE" ("DEPARTMENT_ID", "CHIEF_ID", "NAME", "SALARY") VALUES (4, 0, 'CEO_TestDep_4', 99999999); -- ID: 4
INSERT INTO "EMPLOYEE" ("DEPARTMENT_ID", "CHIEF_ID", "NAME", "SALARY") VALUES (5, 0, 'CEO_TestDep_5', 99999999); -- ID: 5
INSERT INTO "EMPLOYEE" ("DEPARTMENT_ID", "CHIEF_ID", "NAME", "SALARY") VALUES (6, 0, 'CEO_TestDep_6', 99999999); -- ID: 6



INSERT INTO "EMPLOYEE" ("DEPARTMENT_ID", "CHIEF_ID", "NAME", "SALARY") VALUES (1, 1, 'CHEF1_TestDep_1', 99999);  -- ID: 7
INSERT INTO "EMPLOYEE" ("DEPARTMENT_ID", "CHIEF_ID", "NAME", "SALARY") VALUES (1, 1, 'CHEF2_TestDep_1', 99999);  -- ID: 8
INSERT INTO "EMPLOYEE" ("DEPARTMENT_ID", "CHIEF_ID", "NAME", "SALARY") VALUES (1, 1, 'CHEF3_TestDep_1', 99999);  -- ID: 9

INSERT INTO "EMPLOYEE" ("DEPARTMENT_ID", "CHIEF_ID", "NAME", "SALARY") VALUES (2, 2, 'CHEF1_TestDep_2', 89999);  -- ID: 10
INSERT INTO "EMPLOYEE" ("DEPARTMENT_ID", "CHIEF_ID", "NAME", "SALARY") VALUES (2, 2, 'CHEF2_TestDep_2', 89999);  -- ID: 11
INSERT INTO "EMPLOYEE" ("DEPARTMENT_ID", "CHIEF_ID", "NAME", "SALARY") VALUES (2, 2, 'CHEF3_TestDep_2', 89999);  -- ID: 12

INSERT INTO "EMPLOYEE" ("DEPARTMENT_ID", "CHIEF_ID", "NAME", "SALARY") VALUES (3, 3, 'CHEF1_TestDep_3', 79999);  -- ID: 13
INSERT INTO "EMPLOYEE" ("DEPARTMENT_ID", "CHIEF_ID", "NAME", "SALARY") VALUES (3, 3, 'CHEF2_TestDep_3', 79999);  -- ID: 14
INSERT INTO "EMPLOYEE" ("DEPARTMENT_ID", "CHIEF_ID", "NAME", "SALARY") VALUES (3, 3, 'CHEF3_TestDep_3', 79999);  -- ID: 15

INSERT INTO "EMPLOYEE" ("DEPARTMENT_ID", "CHIEF_ID", "NAME", "SALARY") VALUES (4, 4, 'CHEF1_TestDep_4', 69999);  -- ID: 16
INSERT INTO "EMPLOYEE" ("DEPARTMENT_ID", "CHIEF_ID", "NAME", "SALARY") VALUES (4, 4, 'CHEF2_TestDep_4', 69999);  -- ID: 17
INSERT INTO "EMPLOYEE" ("DEPARTMENT_ID", "CHIEF_ID", "NAME", "SALARY") VALUES (4, 4, 'CHEF3_TestDep_4', 69999);  -- ID: 18

INSERT INTO "EMPLOYEE" ("DEPARTMENT_ID", "CHIEF_ID", "NAME", "SALARY") VALUES (5, 5, 'CHEF1_TestDep_5', 59999);  -- ID: 19
INSERT INTO "EMPLOYEE" ("DEPARTMENT_ID", "CHIEF_ID", "NAME", "SALARY") VALUES (5, 5, 'CHEF2_TestDep_5', 59999);  -- ID: 20
INSERT INTO "EMPLOYEE" ("DEPARTMENT_ID", "CHIEF_ID", "NAME", "SALARY") VALUES (5, 5, 'CHEF3_TestDep_5', 59999);  -- ID: 21

INSERT INTO "EMPLOYEE" ("DEPARTMENT_ID", "CHIEF_ID", "NAME", "SALARY") VALUES (6, 6, 'CHEF1_TestDep_6', 49999);  -- ID: 22
INSERT INTO "EMPLOYEE" ("DEPARTMENT_ID", "CHIEF_ID", "NAME", "SALARY") VALUES (6, 6, 'CHEF2_TestDep_6', 49999);  -- ID: 23
INSERT INTO "EMPLOYEE" ("DEPARTMENT_ID", "CHIEF_ID", "NAME", "SALARY") VALUES (6, 6, 'CHEF3_TestDep_6', 49999);  -- ID: 24




INSERT INTO "EMPLOYEE" ("DEPARTMENT_ID", "CHIEF_ID", "NAME", "SALARY") VALUES (1, 7, 'SUBCHEF1_TestDep_1', 9999); -- ID: 25
INSERT INTO "EMPLOYEE" ("DEPARTMENT_ID", "CHIEF_ID", "NAME", "SALARY") VALUES (1, 8, 'SUBCHEF2_TestDep_1', 9999); -- ID: 26
INSERT INTO "EMPLOYEE" ("DEPARTMENT_ID", "CHIEF_ID", "NAME", "SALARY") VALUES (1, 9, 'SUBCHEF2_TestDep_1', 9999); -- ID: 27

INSERT INTO "EMPLOYEE" ("DEPARTMENT_ID", "CHIEF_ID", "NAME", "SALARY") VALUES (2, 10, 'SUBCHEF1_TestDep_2', 9999); -- ID: 28
INSERT INTO "EMPLOYEE" ("DEPARTMENT_ID", "CHIEF_ID", "NAME", "SALARY") VALUES (2, 11, 'SUBCHEF2_TestDep_2', 9999); -- ID: 29
INSERT INTO "EMPLOYEE" ("DEPARTMENT_ID", "CHIEF_ID", "NAME", "SALARY") VALUES (2, 12, 'SUBCHEF2_TestDep_2', 9999); -- ID: 30

INSERT INTO "EMPLOYEE" ("DEPARTMENT_ID", "CHIEF_ID", "NAME", "SALARY") VALUES (3, 13, 'SUBCHEF1_TestDep_3', 9999); -- ID: 31
INSERT INTO "EMPLOYEE" ("DEPARTMENT_ID", "CHIEF_ID", "NAME", "SALARY") VALUES (3, 14, 'SUBCHEF2_TestDep_3', 9999); -- ID: 32
INSERT INTO "EMPLOYEE" ("DEPARTMENT_ID", "CHIEF_ID", "NAME", "SALARY") VALUES (3, 15, 'SUBCHEF2_TestDep_3', 9999); -- ID: 33

INSERT INTO "EMPLOYEE" ("DEPARTMENT_ID", "CHIEF_ID", "NAME", "SALARY") VALUES (4, 16, 'SUBCHEF1_TestDep_4', 9999); -- ID: 34
INSERT INTO "EMPLOYEE" ("DEPARTMENT_ID", "CHIEF_ID", "NAME", "SALARY") VALUES (4, 17, 'SUBCHEF2_TestDep_4', 9999); -- ID: 35
INSERT INTO "EMPLOYEE" ("DEPARTMENT_ID", "CHIEF_ID", "NAME", "SALARY") VALUES (4, 18, 'SUBCHEF2_TestDep_4', 9999); -- ID: 36

INSERT INTO "EMPLOYEE" ("DEPARTMENT_ID", "CHIEF_ID", "NAME", "SALARY") VALUES (5, 19, 'SUBCHEF1_TestDep_5', 9999); -- ID: 37
INSERT INTO "EMPLOYEE" ("DEPARTMENT_ID", "CHIEF_ID", "NAME", "SALARY") VALUES (5, 20, 'SUBCHEF2_TestDep_5', 9999); -- ID: 38
INSERT INTO "EMPLOYEE" ("DEPARTMENT_ID", "CHIEF_ID", "NAME", "SALARY") VALUES (5, 21, 'SUBCHEF2_TestDep_5', 9999); -- ID: 39

INSERT INTO "EMPLOYEE" ("DEPARTMENT_ID", "CHIEF_ID", "NAME", "SALARY") VALUES (6, 22, 'SUBCHEF1_TestDep_6', 9999); -- ID: 40
INSERT INTO "EMPLOYEE" ("DEPARTMENT_ID", "CHIEF_ID", "NAME", "SALARY") VALUES (6, 23, 'SUBCHEF2_TestDep_6', 9999); -- ID: 41
INSERT INTO "EMPLOYEE" ("DEPARTMENT_ID", "CHIEF_ID", "NAME", "SALARY") VALUES (6, 24, 'SUBCHEF2_TestDep_6', 9999); -- ID: 42




INSERT INTO "EMPLOYEE" ("DEPARTMENT_ID", "CHIEF_ID", "NAME", "SALARY") VALUES (1, 25, 'REG_EMPL_TestDep_1_WITH_SUBCHEF25', 1000); -- ID: 43
INSERT INTO "EMPLOYEE" ("DEPARTMENT_ID", "CHIEF_ID", "NAME", "SALARY") VALUES (1, 25, 'REG_EMPL_TestDep_1_WITH_SUBCHEF25', 1000); -- ID: 44

INSERT INTO "EMPLOYEE" ("DEPARTMENT_ID", "CHIEF_ID", "NAME", "SALARY") VALUES (1, 26, 'REG_EMPL_TestDep_1_WITH_SUBCHEF26', 1000); -- ID: 45
INSERT INTO "EMPLOYEE" ("DEPARTMENT_ID", "CHIEF_ID", "NAME", "SALARY") VALUES (1, 26, 'REG_EMPL_TestDep_1_WITH_SUBCHEF26', 1000); -- ID: 46

INSERT INTO "EMPLOYEE" ("DEPARTMENT_ID", "CHIEF_ID", "NAME", "SALARY") VALUES (1, 27, 'REG_EMPL_TestDep_1_WITH_SUBCHEF27', 1000); -- ID: 47
INSERT INTO "EMPLOYEE" ("DEPARTMENT_ID", "CHIEF_ID", "NAME", "SALARY") VALUES (1, 27, 'REG_EMPL_TestDep_1_WITH_SUBCHEF27', 1000); -- ID: 48


INSERT INTO "EMPLOYEE" ("DEPARTMENT_ID", "CHIEF_ID", "NAME", "SALARY") VALUES (2, 28, 'REG_EMPL_TestDep_2_WITH_SUBCHEF28', 1000); -- ID: 49
INSERT INTO "EMPLOYEE" ("DEPARTMENT_ID", "CHIEF_ID", "NAME", "SALARY") VALUES (2, 28, 'REG_EMPL_TestDep_2_WITH_SUBCHEF28', 1000); -- ID: 50

INSERT INTO "EMPLOYEE" ("DEPARTMENT_ID", "CHIEF_ID", "NAME", "SALARY") VALUES (2, 29, 'REG_EMPL_TestDep_2_WITH_SUBCHEF29', 1000); -- ID: 51
INSERT INTO "EMPLOYEE" ("DEPARTMENT_ID", "CHIEF_ID", "NAME", "SALARY") VALUES (2, 29, 'REG_EMPL_TestDep_2_WITH_SUBCHEF29', 1000); -- ID: 52

INSERT INTO "EMPLOYEE" ("DEPARTMENT_ID", "CHIEF_ID", "NAME", "SALARY") VALUES (2, 30, 'REG_EMPL_TestDep_2_WITH_SUBCHEF30', 1000); -- ID: 53
INSERT INTO "EMPLOYEE" ("DEPARTMENT_ID", "CHIEF_ID", "NAME", "SALARY") VALUES (2, 30, 'REG_EMPL_TestDep_2_WITH_SUBCHEF30', 1000); -- ID: 54


INSERT INTO "EMPLOYEE" ("DEPARTMENT_ID", "CHIEF_ID", "NAME", "SALARY") VALUES (3, 31, 'REG_EMPL_TestDep_3_WITH_SUBCHEF31', 1000); -- ID: 55
INSERT INTO "EMPLOYEE" ("DEPARTMENT_ID", "CHIEF_ID", "NAME", "SALARY") VALUES (3, 31, 'REG_EMPL_TestDep_3_WITH_SUBCHEF31', 1000); -- ID: 56

INSERT INTO "EMPLOYEE" ("DEPARTMENT_ID", "CHIEF_ID", "NAME", "SALARY") VALUES (3, 32, 'REG_EMPL_TestDep_3_WITH_SUBCHEF32', 1000); -- ID: 57
INSERT INTO "EMPLOYEE" ("DEPARTMENT_ID", "CHIEF_ID", "NAME", "SALARY") VALUES (3, 32, 'REG_EMPL_TestDep_3_WITH_SUBCHEF32', 1000); -- ID: 58

INSERT INTO "EMPLOYEE" ("DEPARTMENT_ID", "CHIEF_ID", "NAME", "SALARY") VALUES (3, 33, 'REG_EMPL_TestDep_3_WITH_SUBCHEF33', 1000); -- ID: 59
INSERT INTO "EMPLOYEE" ("DEPARTMENT_ID", "CHIEF_ID", "NAME", "SALARY") VALUES (3, 33, 'REG_EMPL_TestDep_3_WITH_SUBCHEF33', 1000); -- ID: 60


INSERT INTO "EMPLOYEE" ("DEPARTMENT_ID", "CHIEF_ID", "NAME", "SALARY") VALUES (4, 34, 'REG_EMPL_TestDep_4_WITH_SUBCHEF34', 1000); -- ID: 61
INSERT INTO "EMPLOYEE" ("DEPARTMENT_ID", "CHIEF_ID", "NAME", "SALARY") VALUES (4, 34, 'REG_EMPL_TestDep_4_WITH_SUBCHEF34', 1000); -- ID: 62

INSERT INTO "EMPLOYEE" ("DEPARTMENT_ID", "CHIEF_ID", "NAME", "SALARY") VALUES (4, 35, 'REG_EMPL_TestDep_4_WITH_SUBCHEF35', 1000); -- ID: 63
INSERT INTO "EMPLOYEE" ("DEPARTMENT_ID", "CHIEF_ID", "NAME", "SALARY") VALUES (4, 35, 'REG_EMPL_TestDep_4_WITH_SUBCHEF35', 1000); -- ID: 64

INSERT INTO "EMPLOYEE" ("DEPARTMENT_ID", "CHIEF_ID", "NAME", "SALARY") VALUES (4, 36, 'REG_EMPL_TestDep_4_WITH_SUBCHEF36', 1000); -- ID: 65
INSERT INTO "EMPLOYEE" ("DEPARTMENT_ID", "CHIEF_ID", "NAME", "SALARY") VALUES (4, 36, 'REG_EMPL_TestDep_4_WITH_SUBCHEF36', 1000); -- ID: 66


INSERT INTO "EMPLOYEE" ("DEPARTMENT_ID", "CHIEF_ID", "NAME", "SALARY") VALUES (5, 37, 'REG_EMPL_TestDep_5_WITH_SUBCHEF37', 1000); -- ID: 67
INSERT INTO "EMPLOYEE" ("DEPARTMENT_ID", "CHIEF_ID", "NAME", "SALARY") VALUES (5, 37, 'REG_EMPL_TestDep_5_WITH_SUBCHEF37', 1000); -- ID: 68

INSERT INTO "EMPLOYEE" ("DEPARTMENT_ID", "CHIEF_ID", "NAME", "SALARY") VALUES (5, 38, 'REG_EMPL_TestDep_5_WITH_SUBCHEF38', 1000); -- ID: 69
INSERT INTO "EMPLOYEE" ("DEPARTMENT_ID", "CHIEF_ID", "NAME", "SALARY") VALUES (5, 38, 'REG_EMPL_TestDep_5_WITH_SUBCHEF38', 1000); -- ID: 70

INSERT INTO "EMPLOYEE" ("DEPARTMENT_ID", "CHIEF_ID", "NAME", "SALARY") VALUES (5, 39, 'REG_EMPL_TestDep_5_WITH_SUBCHEF39', 1000); -- ID: 71
INSERT INTO "EMPLOYEE" ("DEPARTMENT_ID", "CHIEF_ID", "NAME", "SALARY") VALUES (5, 39, 'REG_EMPL_TestDep_5_WITH_SUBCHEF39', 1000); -- ID: 72


INSERT INTO "EMPLOYEE" ("DEPARTMENT_ID", "CHIEF_ID", "NAME", "SALARY") VALUES (6, 40, 'REG_EMPL_TestDep_6_WITH_SUBCHEF40', 1000); -- ID: 73
INSERT INTO "EMPLOYEE" ("DEPARTMENT_ID", "CHIEF_ID", "NAME", "SALARY") VALUES (6, 40, 'REG_EMPL_TestDep_6_WITH_SUBCHEF40', 1000); -- ID: 74

INSERT INTO "EMPLOYEE" ("DEPARTMENT_ID", "CHIEF_ID", "NAME", "SALARY") VALUES (6, 41, 'REG_EMPL_TestDep_6_WITH_SUBCHEF41', 1000); -- ID: 75
INSERT INTO "EMPLOYEE" ("DEPARTMENT_ID", "CHIEF_ID", "NAME", "SALARY") VALUES (6, 41, 'REG_EMPL_TestDep_6_WITH_SUBCHEF41', 1000); -- ID: 76

INSERT INTO "EMPLOYEE" ("DEPARTMENT_ID", "CHIEF_ID", "NAME", "SALARY") VALUES (6, 42, 'REG_EMPL_TestDep_6_WITH_SUBCHEF42', 1000); -- ID: 77
INSERT INTO "EMPLOYEE" ("DEPARTMENT_ID", "CHIEF_ID", "NAME", "SALARY") VALUES (6, 42, 'REG_EMPL_TestDep_6_WITH_SUBCHEF42', 1000); -- ID: 78


INSERT INTO "EMPLOYEE" ("DEPARTMENT_ID", "CHIEF_ID", "NAME", "SALARY") VALUES (4, 64, 'INTERN1', 10); -- ID: 79
INSERT INTO "EMPLOYEE" ("DEPARTMENT_ID", "CHIEF_ID", "NAME", "SALARY") VALUES (2, 54, 'INTERN2', 10); -- ID: 80

INSERT INTO "EMPLOYEE" ("DEPARTMENT_ID", "CHIEF_ID", "NAME", "SALARY") VALUES (2, 80, 'PREINTERN(WANTS_LOT_MONEY_FROM_IT)', -999999999); -- ID: 81

INSERT INTO "EMPLOYEE" ("ID", "DEPARTMENT_ID", "CHIEF_ID", "NAME", "SALARY") VALUES (82, 1, 82, 'ANOTHER_CEO', 89999999999999); --ID: 82
INSERT INTO "EMPLOYEE" ("ID", "DEPARTMENT_ID", "CHIEF_ID", "NAME", "SALARY") VALUES (83, 1, 82, 'ANOTHER_CEOs_SON', 999999); --ID: 83